#!/bin/sh

set -e

cat $1 | \
    sed 's/^ *//;s/ *, */,/' | \
    grep '^[^#]' | \
    awk ' \
/CUT_OUT_BEGIN/ { no_write=1; next; }; \
/CUT_OUT_END/ { no_write=0; next; }; \
{ if (!no_write) print; next; }; \
' - > $2.tmp && \
    mv -f $2.tmp $2 || ( rm $2.tmp && false )

